config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :sales
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :abouts
  resources :events
  resources :contacts
  resources :guest_books
  get '/guestbooks' => 'guest_books#index'

  devise_for :user, 
    path: '', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout'
    }, 
    controllers: {
      sessions: 'users/sessions'
    }

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :products
  get 'home/index'
  get '/home' => 'home#index'

  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/robots.:format', to: "pages#robots"
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/guest_book.rb
class GuestBook < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/sale.rb
class Sale < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/service.rb
class Service < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :item_1_image, ImageUploader
	mount_uploader :item_2_image, ImageUploader
	mount_uploader :item_3_image, ImageUploader
	mount_uploader :item_4_image, ImageUploader
	mount_uploader :item_5_image, ImageUploader
	mount_uploader :item_6_image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable, :recoverable, 
  				:rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.limit(4)
    @events = Event.all.limit(2)
    @abouts = About.all
    @services = Service.all
    @sales = Sale.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def robots
    if canonical_host?
      render 'robots_allow'
    else
      render 'robots_disallow'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :link, :sequence, :status, :sub1_name, :sub1_link, :sub2_name, :sub2_link)
    end

    def canonical_host?
      request.host =~ /sinarmewah\.com/
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:name, :description, :image)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def meta_tag(tag, text)
    content_for :"meta_#{tag}", text
  end

  def yield_meta_tag(tag, default_text='')
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guest_books_helper.rb
module GuestBooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/sales/_form.html.erb
<div class="grid-body">
  <br>
  <%= form_with(model: sales, local: true) do |form| %>
    <% if sales.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(sales.errors.count, "error") %> prohibited this sales from being saved:</h2>

        <ul>
        <% sales.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row pb-1">
      <div class="col-md-2">
        <%= form.label :name, class:"form-label" %>
      </div>
      <div class="col-md-8">
        <%= form.text_field :name, id: :sales_name, :class=> "form-control" %>
      </div>
    </div>
    <div class="row pb-1">
      <div class="col-md-2">
        <%= form.label :description, class:"form-label" %>
      </div>
      <div class="col-md-8">
        <%= form.cktext_area :description, id: :sales_description, :class=> "form-control" %>
      </div>
    </div>
    <div class="row pb-1">
      <div class="col-md-2">
        <%= form.label :image, class:"form-label" %>
      </div>
      <div class="col-md-8">
        <%= form.file_field :image, id: :sales_image, :class=> "form-control" %>
      </div>
    </div>

    <hr>
    <div class="row">
      <div class="col-md-2 p-1">
        <%= link_to 'Back', sales_path, class: "btn btn-secondary btn-block" %>
      </div>
      <div class="col-md-6"></div>
      <div class="col-md-2 p-1"><%= form.submit "Save", class: "btn btn-primary btn-block" %></div>
    
    </div>

  <% end %>
</div>

app/views/sales/_index.html.erb
	<div class="container">
		<div class="row pt-0">
			<div class="col-lg-4 pb-2">
				<H1 class="text-dark">Spare Parts</H1>
			</div>
		</div>
		<div class="row p-1">
      <% @sales.each do |sales| %>
			  <div class="col-lg-3 col-6 pb-2">
			  	<div class="card w-100 p-0 bg-transparent" style="width: 18rem;">
            <% if sales.image? %>
			  			<%= link_to(image_tag(sales.image.thumb.url, alt: "Image #{sales.name}", :class=> "card-img-top bg-white"), sales) if sales.image? %>
            <% else %>
              <img class="card-img-top" src="https://source.unsplash.com/user/erondu/300x300" alt="Card image cap">
            <% end %>
					  <div class="card-body p-1 bg-default text-center" style="
							    position: absolute;
							    bottom: 0;
							    width: 100%;
							">
					  	<h6><%= link_to sales.name, sales, :class=>"text-white text-decoration-none" %></h6>
					  </div>
					</div>
				</div>
			<% end if @sales.present? %>
		</div>
		<% if controller_name == 'home' %>
			<div class="row pt-3 pb-3">
				<div class="col">
					<%= link_to 'More', '/sales', :class=>"btn btn-dark" %>
				</div>
			</div>
		<% end %>
	</div>

app/views/sales/edit.html.erb
<div class="container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="grid simple">
	      <div class="grid-title">
	        <h4>Edit
	          <span class="semi-bold">Spare Part</span>
	        </h4>
	      </div>
			<%= render 'form', sales: @sale %>

	    </div>
	  </div>
	</div>
</div>

app/views/sales/index.html.erb
<% if current_user.present? %>
  <div class="container">
    <div class="row pt-3 pb-3">
      <div class="col-2">
        <%= link_to 'Add', new_sale_path, {:class=>"btn btn-info"} %>
      </div>
      <div class="col-10">
        <h2>Sales</H2>
      </div>
    </div>
    <div class="table-responsive-md">
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col" colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% c=0 %>
          <% @sales.each do |sale| %>
            <tr>
              <td><%= c +=1 %></td>
              <td><%= sale.name %></td>
              <td><%= truncate sale.description, length: 160, :escape => false %></td>
              <td><%= link_to 'Show', sale %></td>
              <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
              <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<% else %>
  <%= render 'sales/index' %>
<% end %>

app/views/sales/new.html.erb
<div class="container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="grid simple">
	      <div class="grid-title">
	        <h4>New
	          <span class="semi-bold">Spare Part</span>
	        </h4>
	      </div>
				<%= render 'form', sales: @sale %>

	    </div>
	  </div>
	</div>
</div>

app/views/sales/show.html.erb
<% meta_tag :title, "#{@sale.name} | Sales" %>
<% meta_tag :description, @sale.description %>
<% meta_tag :keywords, @sale.description %>

<div class="container">
	<div class="border shadow-sm p-3 mb-5 bg-white rounded">
		<div class="row pl-3">
			<h2><strong>Spare Part</strong></h2>
		</div>
		<div class="row pt-3">
		  <div class="col-md-6 pb-3">
		  	<div class="card w-100 p-2" style="width: 18rem;">
		  		<%= image_tag(@sale.image.url, alt: "Image #{@sale.name}", :class=> "card-img-top") if @sale.image? %>
				</div>
			</div>
			<div class="col-md-6">
				<H1><%= @sale.name %></H1>
				<hr>
		    <p class=" h6">
		    	<%= @sale.description.html_safe if @sale.description.present? %>
		    </p>
			</div>

		</div>

    <hr>
    <div class="row">
      <div class="col-md-2 p-1">
      	<% if current_user.present? %>
        	<%= link_to 'Back', sales_path, class: "btn btn-secondary btn-block" %>
        <% else %>
        	<%= link_to 'Back', root_path, class: "btn btn-secondary btn-block" %>
        <% end %>
      </div>
      <div class="col-md-8"></div>
      <div class="col-md-2 p-1">
        <%= link_to 'Edit', edit_sale_path(@sale), class: "btn btn-primary btn-block" if current_user.present? %>
      </div>
    </div>
	</div>
</div>