config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :sales
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :abouts
  resources :events
  resources :contacts
  resources :guest_books
  get '/guestbooks' => 'guest_books#index'

  devise_for :user, 
    path: '', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout'
    }, 
    controllers: {
      sessions: 'users/sessions'
    }

  devise_scope :user do
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :products
  get 'home/index'
  get '/home' => 'home#index'

  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/robots.:format', to: "pages#robots"
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/guest_book.rb
class GuestBook < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/sale.rb
class Sale < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/service.rb
class Service < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :item_1_image, ImageUploader
	mount_uploader :item_2_image, ImageUploader
	mount_uploader :item_3_image, ImageUploader
	mount_uploader :item_4_image, ImageUploader
	mount_uploader :item_5_image, ImageUploader
	mount_uploader :item_6_image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable, :recoverable, 
  				:rememberable, :validatable
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def meta_tag(tag, text)
    content_for :"meta_#{tag}", text
  end

  def yield_meta_tag(tag, default_text='')
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guest_books_helper.rb
module GuestBooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/_carousel.html.erb
<% if @abouts.present? %>
  
  <div class="container">
    <div class="row">
      <% @abouts.each do | about | %>
        <div class="col-md-8 pt-1">
          <div class="grid simple">
            <div class="grid-title">
              <h4 class="text-primary">
                <span class="semi-bold"><%= about.name %> <%= link_to 'Edit', edit_about_path(about) if current_user.present? %></span>
              </h4>
            </div>
            <div class="grid-body">
              <%= about.description_footer.html_safe if about.description_footer.present? %>
            </div>
          </div>
        </div>
        <div class="col-md-4 pt-5 d-none d-sm-block">
        </div>

      <% end if @abouts.present? %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="bg-default p-1"></div>
<footer class="page-footer font-small bg-dark text-white pt-4 copytight_info">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Footer links -->
    <div class="row text-center text-md-left mt-3 pb-3">

      <!-- Grid column -->
      <% if session[:about].present? %>
        <div class="col-md-5 col-lg-5 col-xl-5 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold"><%= session[:about]['name'] %></h6>
          <div>
            <%= truncate session[:about]['description_footer'], length: 250, :escape => false %>
            <%= link_to 'more', '/abouts', :class=>"text-light" %>
          </div>
        </div>
      <% end %>
      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->

      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Sitemap</h6>
        <ul class="list-unstyled">
          <% session[:sitemap].each do |page| %>
            <li class="nav-item p-1">
              <a class="nav-link p-0 text-white" href="/<%= page['link'] %>"><%= page['name'] %></a>
            </li>
          <% end if session[:sitemap].present? %>
        </ul>
      </div>

      <!-- Grid column -->
      <hr class="w-100 clearfix d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
        <% if session[:contact].present? %>
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact <%= link_to 'Edit', "/contacts/#{session[:contact]['id']}/edit" if current_user.present? %></h6>
          <p><i class="<%= session[:contact]['icon_address'] %>"></i> <%= session[:contact]['address'] %></p>
          <p><i class="<%= session[:contact]['icon_email'] %>"></i> <%= session[:contact]['email'] %></p>
          <p><i class="<%= session[:contact]['icon_phone'] %>"></i> <%= session[:contact]['phone'] %></p>
          <p><i class="<%= session[:contact]['icon_fax'] %>"></i> <%= session[:contact]['fax'] %></p>
        <% end %>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Footer links -->

    <hr>

    <!-- Grid row -->
    <div class="row d-flex align-items-center">

      <!-- Grid column -->
      <div class="col-md-7 col-lg-8">

        <!--Copyright-->
        <p class="text-center text-md-left">© <%= DateTime.now().strftime("%Y")%> Copyright:
          <a href="https://vzveda.com" class="text-warning">
            <strong> vzveda.com</strong>
          </a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 ml-lg-0">

        <!-- Social buttons -->
        <div class="text-center text-md-right">
          <ul class="list-unstyled list-inline">
            <% if session[:contact].present? %>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white" href="<%= session[:contact]['facebook'] %>">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>          
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white" href="<%= session[:contact]['twitter'] %>">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white" href="<%= session[:contact]['gplus'] %>">
                  <i class="fab fa-google-plus-g"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white"  href="<%= session[:contact]['linkedin'] %>">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>          
            <% end %>
          </ul>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->


    <!--Start of Tawk.to Script-->
      <script type="text/javascript">
        var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
        (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/5df06cc843be710e1d2187c0/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
        })();
      </script>
    <!--End of Tawk.to Script-->

app/views/layouts/_header.html.erb
<div class="container d-none d-lg-block">
  <div class="row pt-2">
    <div class="col-sm-6 col-xs-12 phone-mail">  
      <ul class="list-unstyled list-inline">
        <li class="text-light">Call : <%= session[:contact]['phone'] if session[:contact].present? %></li>
      </ul>                                  
    </div>
    <div class="col-sm-6 col-xs-12">
      
      <div class="text-center text-md-right">
        <ul class="list-unstyled list-inline">
          <% if session[:contact].present? %>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white" href="<%= session[:contact]['facebook'] %>">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>          
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white" href="<%= session[:contact]['twitter'] %>">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white" href="<%= session[:contact]['gplus'] %>">
                <i class="fab fa-google-plus-g"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-sm rgba-white-slight mx-1 text-white"  href="<%= session[:contact]['linkedin'] %>">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>          
          <% end %>

          <li class="list-inline-item">
            <% if current_user.present? %>
              <a class="btn-floating btn-sm rgba-white-slight mx-1 text-dark " href="/logout" title="Logout">
                <i class="fas fa-sign-out-alt"></i>
              </a>
            <% else %>
              <a class="btn-floating btn-sm rgba-white-slight mx-1 text-dark" href="/login" title="Login">
                <i class="fas fa-sign-in-alt"></i>
              </a>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="den_nav p-1">
  <div class="container-fluid p-1">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-transparent">
      <%= link_to(image_tag(session[:about]['image_thumb'], alt: 'Card image cap', :class=> "d-none d-sm-block pr-3", :width=> "80px"), "/") if session[:about].present? %>
      <div class=" navbar-brand">
        <div class="h5" href="/"><%= session[:about]['name'] if session[:about].present? %>
          <div class="h6 d-none d-sm-block"><small><em>FACTORY AUTOMATION, ELECTRICAL TROUBLESHOOTING & TRADING</em></small></div>
        </div>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarSupportedContent" class="navbar-collapse collapse">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav">
          <% session[:sitemap].each do |page| %>
            <% case page['link'] %>
            <% when 'products' %>          
              <li class="nav-item dropdown p-1">
                <a class="nav-link dropdown-toggle <%= controller_name == page['link'] ? 'text-white' : '' %>" href="#" data-target="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= page['name'] %>
                </a>
                <div class="dropdown-menu bg-default" aria-labelledby="navbarDropdown" id="navbarDropdown" role="menu">
                  <% Product.all.each do |product| %>
                    <%= link_to product.name, product, :class=>"dropdown-item" %>
                  <% end %>
                </div>
              </li>
            <% else %>
              <% if page['sub1_name'].present? %>            
                <li class="nav-item dropdown p-1">
                  <a class="nav-link dropdown-toggle <%= controller_name == page['link'] ? 'text-white' : '' %>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= page['name'] %>
                  </a>
                  <div class="dropdown-menu bg-default" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/<%= page['sub1_link'] %>"><%= page['sub1_name'] %></a>
                    <% if page['sub2_name'].present? %>
                      <a class="dropdown-item" href="/<%= page['sub2_link'] %>"><%= page['sub2_name'] %></a>
                    <% end %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item p-1">
                  <a class="nav-link <%= controller_name == page['link'] ? 'text-white' : '' %>" href="/<%= page['link'] %>"><%= page['name'] %></a>
                </li>
              <% end %>
            <% end %>
          <% end if session[:sitemap].present? %>

        </ul>
      </div>

    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield_meta_tag(:title, 'SINAR MEWAH TEKNIK | FACTORY AUTOMATION, ELECTRICAL TROUBLESHOOTING & TRADING') %></title>
    <%= csrf_meta_tags %>
    <%= canonical_tag -%>
    <% if content_for?(:meta_og) %>
      <%= yield :meta_og %>
    <% else %>
      <meta property="og:title" content="SINAR MEWAH TEKNIK" />
      <meta property="og:description" content="FACTORY AUTOMATION, ELECTRICAL TROUBLESHOOTING & TRADING" />
      <meta property="og:type" content="website" />
      <%= tag :meta, property: 'og:image', content: image_url(session[:about]['image_thumb']) if session[:about].present? %>
    <% end %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='description'
      content='<%= yield_meta_tag(:description, 'FACTORY AUTOMATION, ELECTRICAL TROUBLESHOOTING & TRADING') %>' />
    <meta name='keywords'
      content='<%= yield_meta_tag(:keywords, 'FACTORY AUTOMATION, ELECTRICAL TROUBLESHOOTING & TRADING') %>' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <script src="https://kit.fontawesome.com/1ad6f5e62d.js" crossorigin="anonymous"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag session[:about]['image_thumb'], sizes: '16x16 32x32' if session[:about].present? %>

    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
  	<div class="container-fluid p-0 bg-default">
  		<%= render 'layouts/header' %>
  	</div>
    
	  <%= yield %>
	  <div class="pt-5"></div>
	  <div class="pt-5"></div>
  	<%= render 'layouts/footer' %>

    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "sinarmewah.com",
        "email": "support@sinarmewah.com",
        "url": "https://sinarmewah.com",
        "logo": "https://sinarmewah.com/uploads/about/image/1/logo.png",
        "foundingDate": "2016-03-06",
        "founder": {
          "@type": "Person",
          "name": "Jamalkurniawan"
        },
        "foundingLocation": {
          "@type": "Place",
          "address": "Cikarang, OR"
        }

      }
    </script>
		<!--Start of Tawk.to Script-->
      <script type="text/javascript">
        window.$_Tawk = undefined; 
        var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
        (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/<%= session[:tawk_account_id] %>/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
        })();
      </script>
    <!--End of Tawk.to Script-->

    <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-154421281-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-154421281-1');
      </script>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :page_name %>
  </div>
  <div class="field">
    <%= form.label :sequence %>
    <%= form.number_field :sequence, id: :page_sequence %>
  </div>
  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link, id: :page_link %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :sub1_name %>
    <%= form.text_field :sub1_name, id: :page_sub1_name %>
  </div>
  <div class="field">
    <%= form.label :sub1_link %>
    <%= form.text_field :sub1_link, id: :page_sub1_link %>
  </div>
  <div class="field">
    <%= form.label :sub2_name %>
    <%= form.text_field :sub2_name, id: :page_sub2_name %>
  </div>
  <div class="field">
    <%= form.label :sub2_link %>
    <%= form.text_field :sub2_link, id: :page_sub2_link %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :page_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<H1>Editing Page</H1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<H1>Pages</H1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= page.link %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<H1>New Page</H1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/robots_allow.text.erb
# Allow robots to index the entire site except some specified routes
# rendered when site is visited with the default hostname
# http://www.robotstxt.org/

# ALLOW ROBOTS
User-agent: *
Disallow:
Sitemap: https://sinarmewah.com/sitemap.xml.gz

app/views/pages/robots_disallow.text.erb
# Disallow robots to index any page on the site
# rendered when robot is visiting the site
# via the Cloudfront CDN URL
# to prevent duplicate indexing
# and search results referencing the Cloudfront URL

# DISALLOW ROBOTS
User-agent: *
Disallow: /

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>
<p>
  <strong>Link:</strong>
  <%= @page.link %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>